### ISSUE TITLE
modrobot not detecting newer mod releases in 1.16.1

### ISSUE THREAD

**Issue by medsal15** [calloatti/modrobot#13]
When a mod is updated on curseforge, modrobot does not display the new file in the right columns.
![missing new file for JEI](https://user-images.githubusercontent.com/8267354/86505534-24fdab80-bdc6-11ea-8530-8f0bcd3bd7b5.png)
As the image shows, the line for JEI does not include the newer version (7.0.0.6) of JEI for download.

For some reason, this only happens on mods for 1.16.1, mods for 1.15.2 seem to load the newer releases

**Comment by calloatti** [comment]
The problem is the CurseForge API does not provide the information until there is a final release of Forge for 1.16.1

For now you have to update each mod manually. click this button:

![](https://user-images.githubusercontent.com/12817862/87237285-c25e6e00-c3ca-11ea-8be8-16cd2036ae36.png)

**Comment by medsal15** [comment]
It seems to have fixed itself, and now correctly detects the mod's version.
