### ISSUE TITLE
Version sorting is done alphabetically instead of by semver

### ISSUE THREAD

**Issue by MaryWeeb** [calloatti/modrobot#14]
Versions like 1.15x and 1.16.x are sorted as if they were 1.1.5.x and 1.1.6.x
![image](https://user-images.githubusercontent.com/16361449/90253924-3cf33100-de42-11ea-9622-73822d12414e.png)

**Comment by calloatti** [comment]
the GVERLONG column is for that. And the modloaders window is just informational, it displays the CF API data on forge. That table is used to generate the twitch launcher modpack zip
