### ISSUE TITLE
cf zip crash

### ISSUE THREAD

**Issue by skitzozombie25** [calloatti/modrobot#16]
when creating a   cf  zip   i am given 
DATETIME: 2020-08-14T21:32:35
ERROR   : 13
MESSAGE : Alias 'MODLOADERS_GCF' is not found.
LINENO  : 86
PROGRAM : MR_GENCFMODPACKZIP

this has  happened  since  3.2.0 even now  on 3.3.0
[modrobot.log](https://github.com/calloatti/modrobot/files/5077095/modrobot.log)

**Comment by calloatti** [comment]
Fixed on 3.4.0 If you did not had a chance to get the release, I could send you temporary link.
