### ISSUE TITLE
No releases?

### ISSUE THREAD

**Issue by ITCMD** [calloatti/modrobot#17]
Wiki says to go to releases. When going there, there are no releases available.

**Comment by idkman2021** [comment]
same issue pls fix

**Comment by barraIhsan** [comment]
same, is the project abonded?

**Comment by SpeedRider** [comment]
any updates on this ?

**Comment by calloatti** [comment]
Last public release here:

https://drive.google.com/file/d/1IQnmLWnS1-OcCOO9-osfaIdhy29q_B7r/view?usp=sharing

**Comment by barraIhsan** [comment]
ooo... the owner itself awnsered @SpeedRider @idkman2021 @ITCMD

**Comment by calloatti** [comment]
I deleted all the releases when OverWolf acquired CurseForge to avoid any issues, and to wait and see if there were going to be any drastic policy changes re the CF API  from OverWolf 

Since nothing has changed apparently, I posted that link until I find the time to do a proper new release.

**Comment by barraIhsan** [comment]
Ok

**Comment by ITCMD** [comment]
I appreciate it, and appreciate the explanation as I was put back by it not being hosted on github at first.

I'll close this for now since the question is answered and once you end up posting a release, well, this won't really be a good question anymore :)

**Comment by JoshuaVandaele** [comment]
Hey about that

**Comment by calloatti** [comment]
https://github.com/calloatti/modrobot/releases
