### ISSUE TITLE
1.18 and 1.18.1 support

### ISSUE THREAD

**Issue by Bluscream** [calloatti/modrobot#23]
Would love to P/R it but i won't touch this cursed language.

I think it's in here?
- https://github.com/calloatti/modrobot/blob/master/source/mr_instances.scx.xml#L1498
- https://github.com/calloatti/modrobot/blob/master/source/mr_enum_gameversion.scx.xml

**Comment by JustAnOkapi** [comment]
i think 1.18.1 already works
i tried it today and it found the latest fabric and successfully updated 1.18 mods

**Comment by Bluscream** [comment]
yeah, sorry didn't find the right update button ^^
