### ISSUE TITLE
Cannot launch the program

### ISSUE THREAD

**Issue by G2159687** [calloatti/modrobot#3]
Hi. I wanted to try this app out, but I encountered an error on the startup of the program.

The only error log I can provide is the file below, the program says there is an 'modrobot.err' generated, but it isn't generated actually :(
[modrobot.log](https://github.com/calloatti/modrobot/files/3292656/modrobot.log)

My OS is Windows 7, with .Net 4.7.2 and several VC++ versions installed. Does the program has other dependencies to run?

**Comment by calloatti** [comment]
No other dependencies other than the dlls already included. About the error you get I will try to reproduce it.

**Comment by calloatti** [comment]
Can you tell me in what launguage is your Windows 7 install?

**Comment by G2159687** [comment]
Thanks for your deep investigation! I'll get the new version and see if the problem is fixed as soon as it comes out.

**Comment by calloatti** [comment]
https://github.com/calloatti/modrobot/releases/tag/0.0.30

Check if this release fixes the codepage issue.

**Comment by G2159687** [comment]
The issue is fixed in the latest release. Thanks for your effort, I'll try it out and... report more issues if I find them :P
